image: rust:latest

before_script:
  - apt-get update
  - apt-get install -y libasound2-dev

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build

test_unit:
  stage: test
  script:
    - cargo test

test_integration:
  stage: test
  script:
    - cargo build --release
    - python tests/tests.py
